### ISSUE TITLE
修改密码页中存在的bug

### ISSUE THREAD

**Issue by project-popcorn** [thqy39/thqy39.github.io#1]
您好，我是芝士网的一名普通用户。我发现了一个小漏洞。
（https://www.zhishinet.com/ForgetPasswordPage.html  ） 页中审查元素时，将第四部的display:none去掉可以直接修改密码。
同时祝芝士网越办越火。。

**Comment by thqy39** [comment]
经测试，您所说的问题的确存在。
感谢您对芝士网的大力支持以及您对本产品提出的宝贵意见与善意的提醒，这是我们产品QA的疏漏，我们会尽快修复此BUG。除此之外，我对您技术的热爱表示肯定，希望您日后的技术会越来越好！

芝士网研发人员 致上

**Comment by project-popcorn** [comment]
以前曾经在芝士网吧发过查看答案的破解帖子，后来你们也都修复了，想必也是你们洞察的敏锐。。对以前可能给你们添的麻烦请见谅......没有想到芝士网的运营人员居然还上 Github

**Comment by thqy39** [comment]
对了，请问一下为什么会找到我这里？

**Comment by project-popcorn** [comment]
在 Github 中按Code查找 zhishinet.com，可以找到这里... 只是随便试试而已，没想到还真有。

**Comment by thqy39** [comment]
补充几点：
①我们属于芝士网研发人员，身为码农上Github并不算奇事; 
②产品的代码一定不会放在外网;
③以后发现问题可以直接反应给我们哈，这样不仅有利于身心健康还有利于世界和平🤓，期待下次再会;

芝士网研发人员 致上

**Comment by project-popcorn** [comment]
嗯，好的。感谢您的回复和对我的支持。

另外，其实除了修改密码以外，你们的网站还是有漏洞的，而且不止一个...
比如一个最严重的，一开始我用芝士网的时候就曾经扫过敏感链接，当时扫出来的是https://ids.zhishinet.com/carbon/admin/index.jsp还有一个是www.zhishinet.com ,不过都是403。
后来看到您的博客里有dev.zhishinet.com的地址，然后就顺藤摸瓜找到了  ids-dev.zhishinet.com/carbon/admin/index.jsp ，是200，也就是可以访问。  尝试以后发现你们的admin密码是弱密码，这里就不说了。。然后登上wso2了以后实验了一下，可以随意给用户加减用户组和改role的...   当然，我很快改回来了。。。
还有一个就是你们芝士网会把用户信息存在本地，其中存储有一个项叫做userId，修改以后可以看到别人的芝士币，经验值和成就，这个虽然问题不大但是总是让我觉得你们从不把安全当回事...而且userId改成教师的userId以后还能访问教师页面，虽然不能管理班级...
以及你们的微课堂每天的首次观看是可以加10经验值的，不过一口气打开20个视频然后一起放完居然会算200经验值...微课堂的首次观看似乎是按照在电脑上的日期算的...自己修改电脑上的日期也可以增加经验值...

我知道互联网上攻击者的一次攻击可能会让站长花几十倍的时间来堵住漏洞...但是个人觉得这也是很重要的一方面，尽管芝士网目前还是一个小网站，但是上海市和你们合作的学校当中可能也不乏这种和我一样找漏洞的学生... 

不过我真的很惊讶有你们这样认真负责的工作人员...   也祝汉得知云的发展越来越好！

**Comment by thqy39** [comment]
好的，谢谢您多次的热情反馈。我们是前不久才开始重新整体改造芝士网的，这个过程需要一定的时间，感谢您对此改造起到的加速推进作用，我代表我个人和新的研发人员对您致以崇高的敬意。那本次暂时就到这里吧，以后有任何新的问题，欢迎您再次提出宝贵的意见。
另外，鉴于我们对话间包含部分敏感信息，征求一下您的意见，请允许对此issues进行删除。我已经存档记录，如果您也需要的话，等您处理。

**Comment by project-popcorn** [comment]
我也已经截屏记录了，您可以删除这个issue了。
希望以后有幸相会：）
