### ISSUE TITLE
芝士网 错题本未限制同时打开的窗口数

### ISSUE THREAD

**Issue by bdtbbylzy** [thqy39/thqy39.github.io#4]
![image](https://user-images.githubusercontent.com/29994336/31050823-78127cee-a689-11e7-8c90-1e674c6e08b8.png)
![image](https://user-images.githubusercontent.com/29994336/31050826-8c888e98-a689-11e7-9b97-184c05b25d25.png)
如图，如果打开一个新窗口，复制上图红框中的地址粘贴过去。
![image](https://user-images.githubusercontent.com/29994336/31050835-d5f75762-a689-11e7-8556-2952d387c210.png)
做成这个样子
可以在右边查看答案，左边写答案，骗经验值。。

**Comment by thqy39** [comment]
很高兴再一次收到了您的发现，非常感谢，开发人员已获悉，将尽快修复这些问题，祝您生活愉快。

芝士网研发人员 致上
