### ISSUE TITLE
芝士网 微信管理后台 弱密码

### ISSUE THREAD

**Issue by bdtbbylzy** [thqy39/thqy39.github.io#5]
https://www.zhishinet.com/wechat/Account/Login

账号admin，密码是弱密码。
![image](https://user-images.githubusercontent.com/29994336/31064172-7c0f638c-a76c-11e7-9733-67bf7b266535.png)

**Comment by thqy39** [comment]
很高兴再一次收到了您的发现，非常感谢，开发人员已获悉，将尽快修复这些问题，祝您生活愉快。

芝士网研发人员 致上
