### ISSUE TITLE
芝士网 教师实例 弱密码

### ISSUE THREAD

**Issue by bdtbbylzy** [thqy39/thqy39.github.io#6]
芝士网的教师实例账户（ps_trainer），使用弱密码（wel****123）
![image](https://user-images.githubusercontent.com/29994336/32989712-a2190118-cd56-11e7-9221-13b725150377.png)

此外，芝士网可以绕过“第一次登录必须修改密码”的逻辑，直接访问芝士网StudentClientPc/www/index-pc.html即可。通过这个漏洞，我目前还是保留了原密码不变动。

**Comment by thqy39** [comment]
很高兴再一次收到了您的发现，非常感谢，开发人员已获悉，将尽快修复这些问题，祝您生活愉快。

芝士网研发人员 致上
